// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtb_top_int.h for the primary calling header

#ifndef VERILATED_VTB_TOP_INT___024ROOT_H_
#define VERILATED_VTB_TOP_INT___024ROOT_H_  // guard

#include "verilated.h"
#include "verilated_timing.h"


class Vtb_top_int__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtb_top_int___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ tb_top_int__DOT__clk;
        CData/*0:0*/ tb_top_int__DOT__rst;
        CData/*0:0*/ tb_top_int__DOT__s_wgt_tvalid;
        CData/*0:0*/ tb_top_int__DOT__s_wgt_tlast;
        CData/*0:0*/ tb_top_int__DOT__s_act_tvalid;
        CData/*0:0*/ tb_top_int__DOT__s_act_tlast;
        CData/*0:0*/ tb_top_int__DOT__m_out_tready;
        CData/*0:0*/ tb_top_int__DOT__start;
        CData/*0:0*/ tb_top_int__DOT__busy;
        CData/*0:0*/ tb_top_int__DOT__error;
        CData/*1:0*/ tb_top_int__DOT__cfg_act_type;
        CData/*1:0*/ tb_top_int__DOT__dut__DOT__act_valid_sr;
        CData/*1:0*/ tb_top_int__DOT__dut__DOT__act_last_sr;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__wgt_rd_valid;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__act_rd_valid;
        CData/*3:0*/ tb_top_int__DOT__dut__DOT__pp_out_valid;
        CData/*1:0*/ tb_top_int__DOT__dut__DOT__out_row_cnt;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__out_buf_valid;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__out_mux_valid;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__out_mux_ready;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__fsm_wgt_load_start;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__fsm_enable;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__fsm_clear_acc;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__fsm_wgt_rd_next;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__fsm_act_rd_next;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__fsm_act_rd_rst;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__fsm_bank_swap;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__fsm_acc_valid;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__fsm_m_out_tlast;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__sram_wgt_buf_ready_lat;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__sram_act_buf_ready_lat;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__pp_done_to_fsm;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT____Vcellout__gen_quant__BRA__0__KET____DOT__u_quant__clip_flag;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT____Vcellout__gen_quant__BRA__0__KET____DOT__u_quant__data_out;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT____Vcellout__gen_quant__BRA__1__KET____DOT__u_quant__clip_flag;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT____Vcellout__gen_quant__BRA__1__KET____DOT__u_quant__data_out;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT____Vcellout__gen_quant__BRA__2__KET____DOT__u_quant__clip_flag;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT____Vcellout__gen_quant__BRA__2__KET____DOT__u_quant__data_out;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT____Vcellout__gen_quant__BRA__3__KET____DOT__u_quant__clip_flag;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT____Vcellout__gen_quant__BRA__3__KET____DOT__u_quant__data_out;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__u_wgt_slave__DOT__r_valid;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__u_wgt_slave__DOT__r_last;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__u_wgt_slave__DOT__input_fire;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__u_wgt_slave__DOT__output_fire;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__u_act_slave__DOT__r_valid;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__u_act_slave__DOT__r_last;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__u_act_slave__DOT__output_fire;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__u_sram__DOT__bank_sel;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__u_sram__DOT__wgt_wr_done;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__u_sram__DOT__act_wr_done;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__wgt_load_active;
        CData/*2:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__wgt_load_cnt;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__wgt_load_en;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__0__KET____DOT__gen_col__BRA__0__KET____DOT__pe__DOT__act_reg;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__0__KET____DOT__gen_col__BRA__0__KET____DOT__pe__DOT__wgt_reg;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__0__KET____DOT__gen_col__BRA__0__KET____DOT__pe__DOT__wgt_pipe_reg;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__0__KET____DOT__gen_col__BRA__0__KET____DOT__pe__DOT__ovf_reg;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__0__KET____DOT__gen_col__BRA__1__KET____DOT__pe__DOT__act_reg;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__0__KET____DOT__gen_col__BRA__1__KET____DOT__pe__DOT__wgt_reg;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__0__KET____DOT__gen_col__BRA__1__KET____DOT__pe__DOT__wgt_pipe_reg;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__0__KET____DOT__gen_col__BRA__1__KET____DOT__pe__DOT__ovf_reg;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__0__KET____DOT__gen_col__BRA__2__KET____DOT__pe__DOT__act_reg;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__0__KET____DOT__gen_col__BRA__2__KET____DOT__pe__DOT__wgt_reg;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__0__KET____DOT__gen_col__BRA__2__KET____DOT__pe__DOT__wgt_pipe_reg;
    };
    struct {
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__0__KET____DOT__gen_col__BRA__2__KET____DOT__pe__DOT__ovf_reg;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__0__KET____DOT__gen_col__BRA__3__KET____DOT__pe__DOT__act_reg;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__0__KET____DOT__gen_col__BRA__3__KET____DOT__pe__DOT__wgt_reg;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__0__KET____DOT__gen_col__BRA__3__KET____DOT__pe__DOT__wgt_pipe_reg;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__0__KET____DOT__gen_col__BRA__3__KET____DOT__pe__DOT__ovf_reg;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__1__KET____DOT__gen_col__BRA__0__KET____DOT__pe__DOT__act_reg;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__1__KET____DOT__gen_col__BRA__0__KET____DOT__pe__DOT__wgt_reg;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__1__KET____DOT__gen_col__BRA__0__KET____DOT__pe__DOT__wgt_pipe_reg;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__1__KET____DOT__gen_col__BRA__0__KET____DOT__pe__DOT__ovf_reg;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__1__KET____DOT__gen_col__BRA__1__KET____DOT__pe__DOT__act_reg;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__1__KET____DOT__gen_col__BRA__1__KET____DOT__pe__DOT__wgt_reg;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__1__KET____DOT__gen_col__BRA__1__KET____DOT__pe__DOT__wgt_pipe_reg;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__1__KET____DOT__gen_col__BRA__1__KET____DOT__pe__DOT__ovf_reg;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__1__KET____DOT__gen_col__BRA__2__KET____DOT__pe__DOT__act_reg;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__1__KET____DOT__gen_col__BRA__2__KET____DOT__pe__DOT__wgt_reg;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__1__KET____DOT__gen_col__BRA__2__KET____DOT__pe__DOT__wgt_pipe_reg;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__1__KET____DOT__gen_col__BRA__2__KET____DOT__pe__DOT__ovf_reg;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__1__KET____DOT__gen_col__BRA__3__KET____DOT__pe__DOT__act_reg;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__1__KET____DOT__gen_col__BRA__3__KET____DOT__pe__DOT__wgt_reg;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__1__KET____DOT__gen_col__BRA__3__KET____DOT__pe__DOT__wgt_pipe_reg;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__1__KET____DOT__gen_col__BRA__3__KET____DOT__pe__DOT__ovf_reg;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__2__KET____DOT__gen_col__BRA__0__KET____DOT__pe__DOT__act_reg;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__2__KET____DOT__gen_col__BRA__0__KET____DOT__pe__DOT__wgt_reg;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__2__KET____DOT__gen_col__BRA__0__KET____DOT__pe__DOT__wgt_pipe_reg;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__2__KET____DOT__gen_col__BRA__0__KET____DOT__pe__DOT__ovf_reg;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__2__KET____DOT__gen_col__BRA__1__KET____DOT__pe__DOT__act_reg;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__2__KET____DOT__gen_col__BRA__1__KET____DOT__pe__DOT__wgt_reg;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__2__KET____DOT__gen_col__BRA__1__KET____DOT__pe__DOT__wgt_pipe_reg;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__2__KET____DOT__gen_col__BRA__1__KET____DOT__pe__DOT__ovf_reg;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__2__KET____DOT__gen_col__BRA__2__KET____DOT__pe__DOT__act_reg;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__2__KET____DOT__gen_col__BRA__2__KET____DOT__pe__DOT__wgt_reg;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__2__KET____DOT__gen_col__BRA__2__KET____DOT__pe__DOT__wgt_pipe_reg;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__2__KET____DOT__gen_col__BRA__2__KET____DOT__pe__DOT__ovf_reg;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__2__KET____DOT__gen_col__BRA__3__KET____DOT__pe__DOT__act_reg;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__2__KET____DOT__gen_col__BRA__3__KET____DOT__pe__DOT__wgt_reg;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__2__KET____DOT__gen_col__BRA__3__KET____DOT__pe__DOT__wgt_pipe_reg;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__2__KET____DOT__gen_col__BRA__3__KET____DOT__pe__DOT__ovf_reg;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__3__KET____DOT__gen_col__BRA__0__KET____DOT__pe__DOT__act_reg;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__3__KET____DOT__gen_col__BRA__0__KET____DOT__pe__DOT__wgt_reg;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__3__KET____DOT__gen_col__BRA__0__KET____DOT__pe__DOT__wgt_pipe_reg;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__3__KET____DOT__gen_col__BRA__0__KET____DOT__pe__DOT__ovf_reg;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__3__KET____DOT__gen_col__BRA__1__KET____DOT__pe__DOT__act_reg;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__3__KET____DOT__gen_col__BRA__1__KET____DOT__pe__DOT__wgt_reg;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__3__KET____DOT__gen_col__BRA__1__KET____DOT__pe__DOT__wgt_pipe_reg;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__3__KET____DOT__gen_col__BRA__1__KET____DOT__pe__DOT__ovf_reg;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__3__KET____DOT__gen_col__BRA__2__KET____DOT__pe__DOT__act_reg;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__3__KET____DOT__gen_col__BRA__2__KET____DOT__pe__DOT__wgt_reg;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__3__KET____DOT__gen_col__BRA__2__KET____DOT__pe__DOT__wgt_pipe_reg;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__3__KET____DOT__gen_col__BRA__2__KET____DOT__pe__DOT__ovf_reg;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__3__KET____DOT__gen_col__BRA__3__KET____DOT__pe__DOT__act_reg;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__3__KET____DOT__gen_col__BRA__3__KET____DOT__pe__DOT__wgt_reg;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__3__KET____DOT__gen_col__BRA__3__KET____DOT__pe__DOT__wgt_pipe_reg;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__3__KET____DOT__gen_col__BRA__3__KET____DOT__pe__DOT__ovf_reg;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__u_out_master__DOT__r_valid;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__u_out_master__DOT__r_last;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__u_out_master__DOT__output_fire;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__u_out_master__DOT__input_fire;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__u_fsm__DOT__m_out_tvalid;
        CData/*3:0*/ tb_top_int__DOT__dut__DOT__u_fsm__DOT__state;
        CData/*3:0*/ tb_top_int__DOT__dut__DOT__u_fsm__DOT__next_state;
        CData/*1:0*/ tb_top_int__DOT__dut__DOT__u_fsm__DOT__r_act_type;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__u_fsm__DOT__wgt_load_cnt;
        CData/*3:0*/ tb_top_int__DOT__dut__DOT__u_fsm__DOT__drain_cnt;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__u_fsm__DOT__watchdog_timeout;
    };
    struct {
        CData/*2:0*/ tb_top_int__DOT__dut__DOT__u_fsm__DOT__err_code_reg;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__0__KET____DOT__u_pp__DOT__s1_valid;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__0__KET____DOT__u_pp__DOT__s2_valid;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__0__KET____DOT__u_pp__DOT__s3_valid;
        CData/*3:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__0__KET____DOT__u_pp__DOT__any_sat;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__0__KET____DOT__u_pp__DOT__GEN_STAGE3__BRA__0__KET____DOT__saturated;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__0__KET____DOT__u_pp__DOT__GEN_STAGE3__BRA__0__KET____DOT__pre_act;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__0__KET____DOT__u_pp__DOT__GEN_STAGE3__BRA__1__KET____DOT__saturated;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__0__KET____DOT__u_pp__DOT__GEN_STAGE3__BRA__1__KET____DOT__pre_act;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__0__KET____DOT__u_pp__DOT__GEN_STAGE3__BRA__2__KET____DOT__saturated;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__0__KET____DOT__u_pp__DOT__GEN_STAGE3__BRA__2__KET____DOT__pre_act;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__0__KET____DOT__u_pp__DOT__GEN_STAGE3__BRA__3__KET____DOT__saturated;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__0__KET____DOT__u_pp__DOT__GEN_STAGE3__BRA__3__KET____DOT__pre_act;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__1__KET____DOT__u_pp__DOT__s1_valid;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__1__KET____DOT__u_pp__DOT__s2_valid;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__1__KET____DOT__u_pp__DOT__s3_valid;
        CData/*3:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__1__KET____DOT__u_pp__DOT__any_sat;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__1__KET____DOT__u_pp__DOT__GEN_STAGE3__BRA__0__KET____DOT__saturated;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__1__KET____DOT__u_pp__DOT__GEN_STAGE3__BRA__0__KET____DOT__pre_act;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__1__KET____DOT__u_pp__DOT__GEN_STAGE3__BRA__1__KET____DOT__saturated;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__1__KET____DOT__u_pp__DOT__GEN_STAGE3__BRA__1__KET____DOT__pre_act;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__1__KET____DOT__u_pp__DOT__GEN_STAGE3__BRA__2__KET____DOT__saturated;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__1__KET____DOT__u_pp__DOT__GEN_STAGE3__BRA__2__KET____DOT__pre_act;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__1__KET____DOT__u_pp__DOT__GEN_STAGE3__BRA__3__KET____DOT__saturated;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__1__KET____DOT__u_pp__DOT__GEN_STAGE3__BRA__3__KET____DOT__pre_act;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__2__KET____DOT__u_pp__DOT__s1_valid;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__2__KET____DOT__u_pp__DOT__s2_valid;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__2__KET____DOT__u_pp__DOT__s3_valid;
        CData/*3:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__2__KET____DOT__u_pp__DOT__any_sat;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__2__KET____DOT__u_pp__DOT__GEN_STAGE3__BRA__0__KET____DOT__saturated;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__2__KET____DOT__u_pp__DOT__GEN_STAGE3__BRA__0__KET____DOT__pre_act;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__2__KET____DOT__u_pp__DOT__GEN_STAGE3__BRA__1__KET____DOT__saturated;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__2__KET____DOT__u_pp__DOT__GEN_STAGE3__BRA__1__KET____DOT__pre_act;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__2__KET____DOT__u_pp__DOT__GEN_STAGE3__BRA__2__KET____DOT__saturated;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__2__KET____DOT__u_pp__DOT__GEN_STAGE3__BRA__2__KET____DOT__pre_act;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__2__KET____DOT__u_pp__DOT__GEN_STAGE3__BRA__3__KET____DOT__saturated;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__2__KET____DOT__u_pp__DOT__GEN_STAGE3__BRA__3__KET____DOT__pre_act;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__3__KET____DOT__u_pp__DOT__s1_valid;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__3__KET____DOT__u_pp__DOT__s2_valid;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__3__KET____DOT__u_pp__DOT__s3_valid;
        CData/*3:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__3__KET____DOT__u_pp__DOT__any_sat;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__3__KET____DOT__u_pp__DOT__GEN_STAGE3__BRA__0__KET____DOT__saturated;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__3__KET____DOT__u_pp__DOT__GEN_STAGE3__BRA__0__KET____DOT__pre_act;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__3__KET____DOT__u_pp__DOT__GEN_STAGE3__BRA__1__KET____DOT__saturated;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__3__KET____DOT__u_pp__DOT__GEN_STAGE3__BRA__1__KET____DOT__pre_act;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__3__KET____DOT__u_pp__DOT__GEN_STAGE3__BRA__2__KET____DOT__saturated;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__3__KET____DOT__u_pp__DOT__GEN_STAGE3__BRA__2__KET____DOT__pre_act;
        CData/*0:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__3__KET____DOT__u_pp__DOT__GEN_STAGE3__BRA__3__KET____DOT__saturated;
        CData/*7:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__3__KET____DOT__u_pp__DOT__GEN_STAGE3__BRA__3__KET____DOT__pre_act;
        CData/*0:0*/ __Vdlyvval__tb_top_int__DOT__clk__v0;
        CData/*0:0*/ __Vdlyvset__tb_top_int__DOT__clk__v0;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_top_int__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_top_int__DOT__rst__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_top_int__DOT__busy__0;
        CData/*0:0*/ __Vtrigprevexpr_he392af5f__0;
        CData/*0:0*/ __VactDidInit;
        CData/*0:0*/ __VactContinue;
        SData/*15:0*/ tb_top_int__DOT__cfg_num_ic;
        SData/*15:0*/ tb_top_int__DOT__cfg_num_oc;
        SData/*15:0*/ tb_top_int__DOT__cfg_num_spatial;
        SData/*15:0*/ tb_top_int__DOT__cfg_k_depth;
        SData/*15:0*/ tb_top_int__DOT__cfg_timeout;
        SData/*15:0*/ tb_top_int__DOT__cfg_inv_scale;
    };
    struct {
        SData/*15:0*/ tb_top_int__DOT__cfg_scale_mult;
        SData/*15:0*/ tb_top_int__DOT__dut__DOT__ovf_flat;
        SData/*9:0*/ tb_top_int__DOT__dut__DOT__u_sram__DOT__wgt_wr_ptr;
        SData/*9:0*/ tb_top_int__DOT__dut__DOT__u_sram__DOT__wgt_rd_ptr;
        SData/*8:0*/ tb_top_int__DOT__dut__DOT__u_sram__DOT__act_wr_ptr;
        SData/*8:0*/ tb_top_int__DOT__dut__DOT__u_sram__DOT__act_rd_ptr;
        SData/*15:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__0__KET____DOT__gen_col__BRA__0__KET____DOT__pe__DOT__mult_reg;
        SData/*15:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__0__KET____DOT__gen_col__BRA__1__KET____DOT__pe__DOT__mult_reg;
        SData/*15:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__0__KET____DOT__gen_col__BRA__2__KET____DOT__pe__DOT__mult_reg;
        SData/*15:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__0__KET____DOT__gen_col__BRA__3__KET____DOT__pe__DOT__mult_reg;
        SData/*15:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__1__KET____DOT__gen_col__BRA__0__KET____DOT__pe__DOT__mult_reg;
        SData/*15:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__1__KET____DOT__gen_col__BRA__1__KET____DOT__pe__DOT__mult_reg;
        SData/*15:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__1__KET____DOT__gen_col__BRA__2__KET____DOT__pe__DOT__mult_reg;
        SData/*15:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__1__KET____DOT__gen_col__BRA__3__KET____DOT__pe__DOT__mult_reg;
        SData/*15:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__2__KET____DOT__gen_col__BRA__0__KET____DOT__pe__DOT__mult_reg;
        SData/*15:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__2__KET____DOT__gen_col__BRA__1__KET____DOT__pe__DOT__mult_reg;
        SData/*15:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__2__KET____DOT__gen_col__BRA__2__KET____DOT__pe__DOT__mult_reg;
        SData/*15:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__2__KET____DOT__gen_col__BRA__3__KET____DOT__pe__DOT__mult_reg;
        SData/*15:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__3__KET____DOT__gen_col__BRA__0__KET____DOT__pe__DOT__mult_reg;
        SData/*15:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__3__KET____DOT__gen_col__BRA__1__KET____DOT__pe__DOT__mult_reg;
        SData/*15:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__3__KET____DOT__gen_col__BRA__2__KET____DOT__pe__DOT__mult_reg;
        SData/*15:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__3__KET____DOT__gen_col__BRA__3__KET____DOT__pe__DOT__mult_reg;
        SData/*15:0*/ tb_top_int__DOT__dut__DOT__u_fsm__DOT__r_num_ic;
        SData/*15:0*/ tb_top_int__DOT__dut__DOT__u_fsm__DOT__r_num_oc;
        SData/*15:0*/ tb_top_int__DOT__dut__DOT__u_fsm__DOT__r_num_spatial;
        SData/*15:0*/ tb_top_int__DOT__dut__DOT__u_fsm__DOT__r_k_depth;
        SData/*15:0*/ tb_top_int__DOT__dut__DOT__u_fsm__DOT__r_timeout;
        SData/*15:0*/ tb_top_int__DOT__dut__DOT__u_fsm__DOT__compute_cnt;
        SData/*15:0*/ tb_top_int__DOT__dut__DOT__u_fsm__DOT__cnt_ic;
        SData/*15:0*/ tb_top_int__DOT__dut__DOT__u_fsm__DOT__cnt_oc;
        SData/*15:0*/ tb_top_int__DOT__dut__DOT__u_fsm__DOT__cnt_spatial;
        SData/*15:0*/ tb_top_int__DOT__dut__DOT__u_fsm__DOT__watchdog_cnt;
        IData/*31:0*/ tb_top_int__DOT__s_wgt_tdata;
        VlWide<4>/*127:0*/ tb_top_int__DOT__s_act_tdata;
        IData/*31:0*/ tb_top_int__DOT__perf_total_cycles;
        IData/*31:0*/ tb_top_int__DOT__perf_compute_cycles;
        IData/*31:0*/ tb_top_int__DOT__perf_stall_cycles;
        IData/*31:0*/ tb_top_int__DOT__perf_wgt_load_cycles;
        IData/*31:0*/ tb_top_int__DOT__perf_drain_cycles;
        IData/*31:0*/ tb_top_int__DOT__perf_tile_count;
        IData/*31:0*/ tb_top_int__DOT__perf_overflow_count;
        IData/*31:0*/ tb_top_int__DOT__perf_timeout_count;
        IData/*31:0*/ tb_top_int__DOT__num_wgt_vectors;
        IData/*31:0*/ tb_top_int__DOT__num_act_vectors;
        IData/*31:0*/ tb_top_int__DOT__num_expected;
        IData/*31:0*/ tb_top_int__DOT__pass_count;
        IData/*31:0*/ tb_top_int__DOT__fail_count;
        IData/*31:0*/ tb_top_int__DOT__output_idx;
        IData/*31:0*/ tb_top_int__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ tb_top_int__DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ tb_top_int__DOT__unnamedblk3__DOT__i;
        IData/*31:0*/ tb_top_int__DOT__dut__DOT__wgt_rd_data;
        IData/*31:0*/ tb_top_int__DOT__dut__DOT__act_rd_data;
        IData/*31:0*/ tb_top_int__DOT__dut__DOT__u_wgt_slave__DOT__r_data;
        VlWide<4>/*127:0*/ tb_top_int__DOT__dut__DOT__u_act_slave__DOT__r_data;
        IData/*31:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__0__KET____DOT__gen_col__BRA__0__KET____DOT__pe__DOT__acc_reg;
        IData/*31:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__0__KET____DOT__gen_col__BRA__0__KET____DOT__pe__DOT__sum_next;
        IData/*31:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__0__KET____DOT__gen_col__BRA__1__KET____DOT__pe__DOT__acc_reg;
        IData/*31:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__0__KET____DOT__gen_col__BRA__1__KET____DOT__pe__DOT__sum_next;
        IData/*31:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__0__KET____DOT__gen_col__BRA__2__KET____DOT__pe__DOT__acc_reg;
        IData/*31:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__0__KET____DOT__gen_col__BRA__2__KET____DOT__pe__DOT__sum_next;
        IData/*31:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__0__KET____DOT__gen_col__BRA__3__KET____DOT__pe__DOT__acc_reg;
        IData/*31:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__0__KET____DOT__gen_col__BRA__3__KET____DOT__pe__DOT__sum_next;
        IData/*31:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__1__KET____DOT__gen_col__BRA__0__KET____DOT__pe__DOT__acc_reg;
    };
    struct {
        IData/*31:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__1__KET____DOT__gen_col__BRA__0__KET____DOT__pe__DOT__sum_next;
        IData/*31:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__1__KET____DOT__gen_col__BRA__1__KET____DOT__pe__DOT__acc_reg;
        IData/*31:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__1__KET____DOT__gen_col__BRA__1__KET____DOT__pe__DOT__sum_next;
        IData/*31:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__1__KET____DOT__gen_col__BRA__2__KET____DOT__pe__DOT__acc_reg;
        IData/*31:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__1__KET____DOT__gen_col__BRA__2__KET____DOT__pe__DOT__sum_next;
        IData/*31:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__1__KET____DOT__gen_col__BRA__3__KET____DOT__pe__DOT__acc_reg;
        IData/*31:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__1__KET____DOT__gen_col__BRA__3__KET____DOT__pe__DOT__sum_next;
        IData/*31:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__2__KET____DOT__gen_col__BRA__0__KET____DOT__pe__DOT__acc_reg;
        IData/*31:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__2__KET____DOT__gen_col__BRA__0__KET____DOT__pe__DOT__sum_next;
        IData/*31:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__2__KET____DOT__gen_col__BRA__1__KET____DOT__pe__DOT__acc_reg;
        IData/*31:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__2__KET____DOT__gen_col__BRA__1__KET____DOT__pe__DOT__sum_next;
        IData/*31:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__2__KET____DOT__gen_col__BRA__2__KET____DOT__pe__DOT__acc_reg;
        IData/*31:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__2__KET____DOT__gen_col__BRA__2__KET____DOT__pe__DOT__sum_next;
        IData/*31:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__2__KET____DOT__gen_col__BRA__3__KET____DOT__pe__DOT__acc_reg;
        IData/*31:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__2__KET____DOT__gen_col__BRA__3__KET____DOT__pe__DOT__sum_next;
        IData/*31:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__3__KET____DOT__gen_col__BRA__0__KET____DOT__pe__DOT__acc_reg;
        IData/*31:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__3__KET____DOT__gen_col__BRA__0__KET____DOT__pe__DOT__sum_next;
        IData/*31:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__3__KET____DOT__gen_col__BRA__1__KET____DOT__pe__DOT__acc_reg;
        IData/*31:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__3__KET____DOT__gen_col__BRA__1__KET____DOT__pe__DOT__sum_next;
        IData/*31:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__3__KET____DOT__gen_col__BRA__2__KET____DOT__pe__DOT__acc_reg;
        IData/*31:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__3__KET____DOT__gen_col__BRA__2__KET____DOT__pe__DOT__sum_next;
        IData/*31:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__3__KET____DOT__gen_col__BRA__3__KET____DOT__pe__DOT__acc_reg;
        IData/*31:0*/ tb_top_int__DOT__dut__DOT__u_array__DOT__gen_row__BRA__3__KET____DOT__gen_col__BRA__3__KET____DOT__pe__DOT__sum_next;
        IData/*31:0*/ tb_top_int__DOT__dut__DOT__u_out_master__DOT__r_data;
        IData/*31:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__0__KET____DOT__u_pp__DOT__STAGE1__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__0__KET____DOT__u_pp__DOT__STAGE1__DOT__unnamedblk2__DOT__c;
        IData/*31:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__1__KET____DOT__u_pp__DOT__STAGE1__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__1__KET____DOT__u_pp__DOT__STAGE1__DOT__unnamedblk2__DOT__c;
        IData/*31:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__2__KET____DOT__u_pp__DOT__STAGE1__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__2__KET____DOT__u_pp__DOT__STAGE1__DOT__unnamedblk2__DOT__c;
        IData/*31:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__3__KET____DOT__u_pp__DOT__STAGE1__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ tb_top_int__DOT__dut__DOT__gen_pp__BRA__3__KET____DOT__u_pp__DOT__STAGE1__DOT__unnamedblk2__DOT__c;
        IData/*31:0*/ __VactIterCount;
        QData/*47:0*/ tb_top_int__DOT__dut__DOT__gen_quant__BRA__0__KET____DOT__u_quant__DOT__scaled_reg;
        QData/*47:0*/ tb_top_int__DOT__dut__DOT__gen_quant__BRA__1__KET____DOT__u_quant__DOT__scaled_reg;
        QData/*47:0*/ tb_top_int__DOT__dut__DOT__gen_quant__BRA__2__KET____DOT__u_quant__DOT__scaled_reg;
        QData/*47:0*/ tb_top_int__DOT__dut__DOT__gen_quant__BRA__3__KET____DOT__u_quant__DOT__scaled_reg;
        VlUnpacked<IData/*31:0*/, 4> tb_top_int__DOT__cfg_bias;
        VlUnpacked<IData/*31:0*/, 1024> tb_top_int__DOT__wgt_stimulus;
        VlUnpacked<IData/*31:0*/, 512> tb_top_int__DOT__act_stimulus;
        VlUnpacked<CData/*7:0*/, 4> tb_top_int__DOT__dut__DOT__wgt_in_arr;
        VlUnpacked<CData/*7:0*/, 4> tb_top_int__DOT__dut__DOT__act_in_arr;
        VlUnpacked<VlUnpacked<IData/*31:0*/, 4>, 4> tb_top_int__DOT__dut__DOT__acc_out_arr;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 4>, 4> tb_top_int__DOT__dut__DOT__overflow_arr;
        VlUnpacked<VlUnpacked<CData/*7:0*/, 4>, 4> tb_top_int__DOT__dut__DOT__pp_data_out;
        VlUnpacked<IData/*31:0*/, 4> tb_top_int__DOT__dut__DOT__pp_packed;
        VlUnpacked<IData/*31:0*/, 4> tb_top_int__DOT__dut__DOT__out_buf;
        VlUnpacked<CData/*7:0*/, 4> tb_top_int__DOT__dut__DOT____Vcellout__gen_pp__BRA__0__KET____DOT__u_pp__data_out;
        VlUnpacked<IData/*31:0*/, 4> tb_top_int__DOT__dut__DOT____Vcellinp__gen_pp__BRA__0__KET____DOT__u_pp__acc_in;
        VlUnpacked<CData/*7:0*/, 4> tb_top_int__DOT__dut__DOT____Vcellout__gen_pp__BRA__1__KET____DOT__u_pp__data_out;
        VlUnpacked<IData/*31:0*/, 4> tb_top_int__DOT__dut__DOT____Vcellinp__gen_pp__BRA__1__KET____DOT__u_pp__acc_in;
        VlUnpacked<CData/*7:0*/, 4> tb_top_int__DOT__dut__DOT____Vcellout__gen_pp__BRA__2__KET____DOT__u_pp__data_out;
        VlUnpacked<IData/*31:0*/, 4> tb_top_int__DOT__dut__DOT____Vcellinp__gen_pp__BRA__2__KET____DOT__u_pp__acc_in;
        VlUnpacked<CData/*7:0*/, 4> tb_top_int__DOT__dut__DOT____Vcellout__gen_pp__BRA__3__KET____DOT__u_pp__data_out;
        VlUnpacked<IData/*31:0*/, 4> tb_top_int__DOT__dut__DOT____Vcellinp__gen_pp__BRA__3__KET____DOT__u_pp__acc_in;
        VlUnpacked<IData/*31:0*/, 1024> tb_top_int__DOT__dut__DOT__u_sram__DOT__wgt_bank_a;
        VlUnpacked<IData/*31:0*/, 1024> tb_top_int__DOT__dut__DOT__u_sram__DOT__wgt_bank_b;
        VlUnpacked<IData/*31:0*/, 512> tb_top_int__DOT__dut__DOT__u_sram__DOT__act_sram;
        VlUnpacked<VlUnpacked<CData/*7:0*/, 5>, 4> tb_top_int__DOT__dut__DOT__u_array__DOT__act_h;
        VlUnpacked<VlUnpacked<CData/*7:0*/, 4>, 5> tb_top_int__DOT__dut__DOT__u_array__DOT__wgt_v;
        VlUnpacked<CData/*7:0*/, 1024> tb_top_int__DOT__dut__DOT__gen_pp__BRA__0__KET____DOT__u_pp__DOT__gelu_lut;
        VlUnpacked<QData/*47:0*/, 4> tb_top_int__DOT__dut__DOT__gen_pp__BRA__0__KET____DOT__u_pp__DOT__s1_scaled;
        VlUnpacked<QData/*48:0*/, 4> tb_top_int__DOT__dut__DOT__gen_pp__BRA__0__KET____DOT__u_pp__DOT__s2_biased;
        VlUnpacked<CData/*7:0*/, 4> tb_top_int__DOT__dut__DOT__gen_pp__BRA__0__KET____DOT__u_pp__DOT__s3_data;
    };
    struct {
        VlUnpacked<CData/*7:0*/, 1024> tb_top_int__DOT__dut__DOT__gen_pp__BRA__1__KET____DOT__u_pp__DOT__gelu_lut;
        VlUnpacked<QData/*47:0*/, 4> tb_top_int__DOT__dut__DOT__gen_pp__BRA__1__KET____DOT__u_pp__DOT__s1_scaled;
        VlUnpacked<QData/*48:0*/, 4> tb_top_int__DOT__dut__DOT__gen_pp__BRA__1__KET____DOT__u_pp__DOT__s2_biased;
        VlUnpacked<CData/*7:0*/, 4> tb_top_int__DOT__dut__DOT__gen_pp__BRA__1__KET____DOT__u_pp__DOT__s3_data;
        VlUnpacked<CData/*7:0*/, 1024> tb_top_int__DOT__dut__DOT__gen_pp__BRA__2__KET____DOT__u_pp__DOT__gelu_lut;
        VlUnpacked<QData/*47:0*/, 4> tb_top_int__DOT__dut__DOT__gen_pp__BRA__2__KET____DOT__u_pp__DOT__s1_scaled;
        VlUnpacked<QData/*48:0*/, 4> tb_top_int__DOT__dut__DOT__gen_pp__BRA__2__KET____DOT__u_pp__DOT__s2_biased;
        VlUnpacked<CData/*7:0*/, 4> tb_top_int__DOT__dut__DOT__gen_pp__BRA__2__KET____DOT__u_pp__DOT__s3_data;
        VlUnpacked<CData/*7:0*/, 1024> tb_top_int__DOT__dut__DOT__gen_pp__BRA__3__KET____DOT__u_pp__DOT__gelu_lut;
        VlUnpacked<QData/*47:0*/, 4> tb_top_int__DOT__dut__DOT__gen_pp__BRA__3__KET____DOT__u_pp__DOT__s1_scaled;
        VlUnpacked<QData/*48:0*/, 4> tb_top_int__DOT__dut__DOT__gen_pp__BRA__3__KET____DOT__u_pp__DOT__s2_biased;
        VlUnpacked<CData/*7:0*/, 4> tb_top_int__DOT__dut__DOT__gen_pp__BRA__3__KET____DOT__u_pp__DOT__s3_data;
        VlUnpacked<CData/*0:0*/, 8> __Vm_traceActivity;
    };
    std::string tb_top_int__DOT__wgt_file;
    std::string tb_top_int__DOT__act_file;
    std::string tb_top_int__DOT__out_file;
    VlDelayScheduler __VdlySched;
    VlTriggerScheduler __VtrigSched_hc1be2c8c__0;
    VlForkSync __Vfork_1__sync;
    VlTriggerScheduler __VtrigSched_h3a2e7aa0__0;
    VlTriggerScheduler __VtrigSched_h43a5e771__0;
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<5> __VactTriggered;
    VlTriggerVec<5> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vtb_top_int__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vtb_top_int___024root(Vtb_top_int__Syms* symsp, const char* v__name);
    ~Vtb_top_int___024root();
    VL_UNCOPYABLE(Vtb_top_int___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
